name: Rspamd - rapid spam filtering system.
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 3
paginate_path: "blog/page:num"
description: Rspamd home.
future: true
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
